var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:9545"));
// artifacts.require is similar to require in node
const Escrow = artifacts.require('../../contracts/escrow.sol');
// callback function takes in accounts generated by truffle test server
contract('Escrow', function (accounts) {

    it("sets up contract", async function() {
        const contract = await Escrow.deployed();
        const approver = await contract.approver.call();
        assert.equal(approver, 0xabeD470Cf6aebce5530A363E0F5f8334A9A252f4, "No match")
    })

    it('takes a deposit', async function () {
      const contract = await Escrow.deployed();
      await contract.deposit(accounts[0], { value: 1e+18, from: accounts[1] });
      var balance = await web3.eth.getBalance(contract.address);
      assert.equal(balance, 1e+18, "amount did not match");
    });
})